development:
  adapter: postgresql
  encoding: utf8
  database: WebRtc_development
  pool: 5
  username: postgres
  password: tiatrosdev
  port: 5432
  min_messages: WARNING


test: 
  adapter: postgresql
  encoding: utf8
  database: WebRtc_test
  pool: 5
  username: postgres
  password: tiatrosdev
  port: 5432
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: utf8
  database: WebRtc_production
  pool: 5
  username: postgres
  password: tiatrosdev
  port: 5432
  min_messages: WARNING
